apiVersion: kubeadm.k8s.io/v1beta2
kind: ClusterConfiguration
kubernetesVersion: v1.28.0
controlPlaneEndpoint: "$(hostname)"
networking:
  podSubnet: 10.244.0.0/16
apiServer:
  extraArgs:
    ignore-preflight-errors: "all"
featureGates:
  SidecarContainers: true
---
apiVersion: kubeadm.k8s.io/v1beta2
kind: InitConfiguration
nodeRegistration:
  criSocket: "unix:///run/containerd/containerd.sock"
  ignorePreflightErrors:
  - all
---
apiVersion: kubeadm.k8s.io/v1beta2
kind: JoinConfiguration
nodeRegistration:
  criSocket: "unix:///run/containerd/containerd.sock"

